version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - data:/data/db2
    networks:
      - node
volumes:
  data:
    driver: local
networks:
  node:
    driver: bridge